### ISSUE TITLE
update for iOS13

### ISSUE THREAD

**Issue by MiRO92** [autopear/ipainstaller#23]
Hi, can you please update it for iOS 13?

**Comment by hongsolo9** [comment]
https://github.com/hongsolo9/ipainstaller/releases/tag/3.4.1 

Hope this helps!

**Comment by bensh** [comment]
Creating new tweak for iOS 15.
Verified working on palera1n rootless 15.6

Only has -i and -l flags, as that's what I use it for, but happy to add others back in.

**Comment by hongsolo9** [comment]
Thanks for reaching out. That’s strange. I’ll look into this.
