### ISSUE TITLE
Unable to install IPA with Custom Bundle Identifier

### ISSUE THREAD

**Issue by metaljay** [autopear/ipainstaller#8]
Hi,

I am experimenting with an app that has a custom bundle identifier. After changing this i am unable to install the app via command line, i just get 'failed to install'

To replicate what I've done, open Snapchat (easiest to reproduce) and change the bundle identifier.
heres an screen shot to show what i mean (i simply added '1' at the end of the bundle): http://s11.postimg.org/m0drollwz/Screen_Shot_2015_01_03_at_12_23_39.png

When i repackage the payload it fails to install, i previously posted this on reddit but no luck :(

http://www.reddit.com/r/jailbreak/comments/2naqzp/ipa_installations_fail/

(iphone 6, with app sync unified installed)

**Comment by autopear** [comment]
I have tried one and it can install correctly. So your case must be a wrong
package.

If you have iFunBox, you can try to replace the Info.plist of an installed
app, and back up it to IPA, then restore the original Info.plist. The ipa
you just backed up will use the modified Info.plist.

Also the image you posted is too small, maybe you can directly post the
content of Info.plist.

**Comment by metaljay** [comment]
sorry the delay getting back to you, I have tried various ways of editing the info.plist then backing up the IPA but still no luck...

You say you have managed to install it correctly? How did you get both the normal and modified app in the same instance? 

Here is the info.plist, all I have changed is the 'Bundle display name' (to Starcraft from Snapchat) and the 'Bundle identifier' (to com.toyopagroup.picaboo1 from com.toyopagroup.picaboo).
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>14B25</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Starcraft</string>
	<key>CFBundleExecutable</key>
	<string>Snapchat</string>
	<key>CFBundleIcons</key>
	<dict>
		<key>CFBundlePrimaryIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string>AppIcon29x29</string>
				<string>AppIcon40x40</string>
				<string>AppIcon57x57</string>
				<string>AppIcon60x60</string>
			</array>
		</dict>
	</dict>
	<key>CFBundleIcons~ipad</key>
	<dict>
		<key>CFBundlePrimaryIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string>AppIcon29x29</string>
				<string>AppIcon40x40</string>
				<string>AppIcon57x57</string>
				<string>AppIcon60x60</string>
				<string>AppIcon50x50</string>
				<string>AppIcon72x72</string>
			</array>
		</dict>
	</dict>
	<key>CFBundleIdentifier</key>
	<string>com.toyopagroup.picaboo1</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Snapchat</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>8.1.1</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>iPhoneOS</string>
	</array>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>com.toyopagroup.picaboo</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb252151381489775</string>
				<string>snapchat</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>8.1.0.12</string>
	<key>CRITTERCISM_IDENTIFIER</key>
	<string>5364372e1787844e2f000007</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>12B411</string>
	<key>DTPlatformName</key>
	<string>iphoneos</string>
	<key>DTPlatformVersion</key>
	<string>8.1</string>
	<key>DTSDKBuild</key>
	<string>12B411</string>
	<key>DTSDKName</key>
	<string>iphoneos8.1</string>
	<key>DTXcode</key>
	<string>0611</string>
	<key>DTXcodeBuild</key>
	<string>6A2008a</string>
	<key>HOCKEYAPP_IDENTIFIER</key>
	<string></string>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.photography</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>MinimumOSVersion</key>
	<string>6.0</string>
	<key>NSContactsUsageDescription</key>
	<string>The contacts in your address book will be collected by Snapchat.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Certain features, like Smart Filters and Our Story, require your location.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Snapchat needs access to your photos to save Snaps or use images from your camera roll.</string>
	<key>SCGroupIdentifier</key>
	<string>group.snapchat.picaboo</string>
	<key>SCKeychainAccessIdentifier</key>
	<string>3MY7A92V5W.com.toyopagroup.picaboo</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
	</array>
	<key>UILaunchImageFile</key>
	<string>LaunchImage</string>
	<key>UILaunchImages</key>
	<array>
		<dict>
			<key>UILaunchImageMinimumOSVersion</key>
			<string>8.0</string>
			<key>UILaunchImageName</key>
			<string>LaunchImage-800-Portrait-736h</string>
			<key>UILaunchImageOrientation</key>
			<string>Portrait</string>
			<key>UILaunchImageSize</key>
			<string>{414, 736}</string>
		</dict>
		<dict>
			<key>UILaunchImageMinimumOSVersion</key>
			<string>8.0</string>
			<key>UILaunchImageName</key>
			<string>LaunchImage-800-667h</string>
			<key>UILaunchImageOrientation</key>
			<string>Portrait</string>
			<key>UILaunchImageSize</key>
			<string>{375, 667}</string>
		</dict>
		<dict>
			<key>UILaunchImageMinimumOSVersion</key>
			<string>7.0</string>
			<key>UILaunchImageName</key>
			<string>LaunchImage-700</string>
			<key>UILaunchImageOrientation</key>
			<string>Portrait</string>
			<key>UILaunchImageSize</key>
			<string>{320, 480}</string>
		</dict>
		<dict>
			<key>UILaunchImageMinimumOSVersion</key>
			<string>7.0</string>
			<key>UILaunchImageName</key>
			<string>LaunchImage-700-568h</string>
			<key>UILaunchImageOrientation</key>
			<string>Portrait</string>
			<key>UILaunchImageSize</key>
			<string>{320, 568}</string>
		</dict>
	</array>
	<key>UIPrerenderedIcon</key>
	<true/>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>still-camera</string>
	</array>
	<key>UIStatusBarHidden</key>
	<true/>
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleBlackOpaque</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

**Comment by metaljay** [comment]
here is the IPA file with the editted 'info.plist'

https://www.sendspace.com/file/dffkwo

Are you able to install this?

**Comment by autopear** [comment]
Just took a look at the console output from Xcode

"/private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.XSSkHo/extracted/Payload/Starcraft.app/PlugIns/SnapchatShareExt.appex" with identifier "com.toyopagroup.picaboo.share" does not have expected identifier prefix "com.toyopagroup.picaboo1."

**Comment by metaljay** [comment]
Thanks for getting back to me, I've just changed the info.plist at /plugins to reflect the different identifier and it still fails.

Are you able to install it after doing the same?

Thanks for all your help on this.

**Comment by autopear** [comment]
You need to change the plugin's identifier to 'com.toyopagroup.picaboo1.share'.

Also be aware that signed IPA contains your personal information, do not publish any purchased IPA directly on web.

**Comment by autopear** [comment]
Another solution: you can delete the Plugins folder from the IPA an then install (though you will lose the share function).

BTW, I have tried your IPA, after modified the plugin's Info.plist I can successfully install it, though it cannot run because that app is not purchased by me.

**Comment by metaljay** [comment]
It now installs after deleting the plugins folder but does not run? Just opens and closes? I purchased the app (even though it's free), any ideas?

Regards

Jordan Fern

**Comment by autopear** [comment]
You can directly modify the IPA file on Windows, the file system does not matter. On Mac, the system will automatically add some hidden files to the archive if you zip the folder using the Mac's Compress function.

If you don't know how to use the command line zip function, you can decompress the IPA file, and modify the 2 Info.plist files, than drag the *.app folder directly to iTunes, iTunes will pack the folder into a clean IPA file.

**Comment by metaljay** [comment]
I made all the plist changes on my device using iFile, then backed up the app using -b then installed the app using -c
Once it installs and I reboot the app still opens and crashes.

Would it help if I upload my bundle again and you tried to install?

Regards

Jordan Fern

**Comment by metaljay** [comment]
I think the app crashes as it does not have the correct /var/mobile/container/data/application folder location. 

Changing the bundle identifier seems to mess this up

Regards

Jordan

**Comment by autopear** [comment]
You can send me the original SnapChat ipa file.

**Comment by metaljay** [comment]
The app is free on the AppStore, failing that I can upload it if you like?

Regards

Jordan Fern

**Comment by autopear** [comment]
I know, but there is no problem to install it on my own. I can help you
modify your IPA.

**Comment by metaljay** [comment]
Ive uploaded 2 IPA's.
My goal is to have both apps, installed, each with its own login details (as i have 2 accounts).

In order to do that, I thought the easiest way was to just change the bundle identifier, but thats causing issues when it comes to the keychain (as the password for each login is automatically saved).

Here is the standard clean IPA: https://www.sendspace.com/file/z1ruur

Here is my custom IPA (which has the com.toyopagroup.picaboo1.share and com.toyopagroup.picaboo1 added to the required plist and the custom name): https://www.sendspace.com/file/duanj1

I can't thank you enough for helping me out here!

**Comment by autopear** [comment]
It's normal if some application use hard-coded identifier for keychain or some registration credentials. In this case if you want to duplicate the app, you need to write some tweak to modify it. However, this may still not work in some cases.

**Comment by metaljay** [comment]
Thanks for all your support on this, I think I've hit a dead end, I imagine this was why the app 'social duplicator' which used your program has been dropped.

Thanks again :)

**Comment by metaljay** [comment]
Thinking about It; this app worked on ios7, so it's something ios8 has introduced...
